on:
  push:
    branches:
      - master
  release:
    types:
    - created
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Churn
      id: churn
      run: git log --all -M -C --name-only --format='format:' "$@" | sort | grep -v '^$' | uniq -c | sort -n 
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: 1
        body: |
          This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - ${{ steps.churn.outputs }}

